# Schema for the configuration files of the Update module.

advupdate.settings:
  type: config_object
  label: 'Update settings'
  mapping:
    notification:
      type: mapping
      label: 'Notification settings'
      mapping:
        extend_email_report:
          type: boolean
          label: 'Expand the report using "Update Manager Advanced" module'
